### PR TITLE
[BUGFIX] Remove duplicated methods

### PR DESCRIPTION
**Pull request by e0ipso**
Duplicated methods were causing PHP errors.

### CODE REVIEW

**Comment by e0ipso** [comment]
Please @amitaibu merge this branch into #10 :arrow_right: #9 :arrow_right: #8 :arrow_right: #7 :arrow_right: #6 :arrow_right: https://github.com/RESTful-Drupal/restful/pull/620 :arrow_right: `7.x-2.x`

**Comment by amitaibu** [comment]
The PR is against your own repo, it should be against the `RESTful-Drupal/restful`, one no?

Anyway, it can be merged :)

**Comment by amitaibu** [comment]
actually, I don't see them duplicated. what errors do they cause?

**Comment by e0ipso** [comment]
they merge into branches that end in changing RESTful-Drupal#620

**Pull request merged**
